config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :pins
  root 'pins#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user

  has_attached_file :image, :styles => {:medium => "300x300>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:name, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyPinterest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pins/_form.html.haml
= simple_form_for @pin, html: {multipart: true} do |f|
  - if @pin.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pin.errors.count, "error")} prohibited this pin from being saved:"
      %ul
        - @pin.errors.full_messages.each do |msg|
          %li= msg

  =f.input :image
  =f.input :name
  =f.input :description
  =f.button :submit, class: "btn"

app/views/pins/edit.html.haml
%h1 Editingthe pin

=image_tag @pin.image.url
= render 'form'

app/views/pins/index.html.haml
%h1 Listing pins
- @pins.each do |pin|
  -if (File.basename(pin.image.url) != "missing.png")
    =image_tag pin.image.url(:medium)
  %h2
    =link_to pin.name, pin
  %p.user
    Submitted by
    =current_user.email
  
  = link_to 'Show', pin_path(pin)
  = link_to 'Edit', edit_pin_path(pin)
  = link_to 'Destroy', pin, :method => :delete, :data => { :confirm => 'Are you sure?' }
%br
= link_to 'New Pin', new_pin_path

app/views/pins/new.html.haml
%h1 New pin

= render 'form'

= link_to 'Back', pins_path

app/views/pins/show.html.haml
%p#notice= notice
=image_tag @pin.image.url
%h1= @pin.name
%h2= @pin.description
%br/

= link_to 'Edit', edit_pin_path(@pin)
\|
= link_to 'Back', pins_path